#!/bin/bash
export CUBEAPPPATH=`pwd` 
export CUBE_APP_PLUGIN=$CUBEAPPPATH/plugin/:$CUBE_APP_PLUGIN
export CUBE_DEFINE_PATH=$CUBE_TCM_PATH/define:$CUBE_DEFINE_PATH
export CUBE_DEFINE_PATH=$CUBE_TCM_PLUGIN/define:$CUBE_DEFINE_PATH
export CUBE_DEFINE_PATH=$CUBEAPPPATH/define:$CUBE_DEFINE_PATH
export LD_LIBRARY_PATH=$CUBEAPPPATH/locallib/:$LD_LIBRARY_PATH
